// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using STEM.Web.Data;

#nullable disable

namespace STEM.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260516153616_AddPayrollSystem")]
    partial class AddPayrollSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("STEM.Web.Models.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AiEvaluation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AiProcessStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsExcused")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPresent")
                        .HasColumnType("bit");

                    b.Property<string>("ProductMediaUrls")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("TeacherRawNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoTranscript")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Attendan__3214EC07CBE09DDC");

                    b.HasIndex("SessionId");

                    b.HasIndex(new[] { "StudentId" }, "IX_Attendances_StudentId");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("STEM.Web.Models.AttendanceSkillScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttendanceId")
                        .HasColumnType("int");

                    b.Property<string>("Feedback")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AttendanceId" }, "IX_AttendanceSkillScores_AttendanceId");

                    b.ToTable("AttendanceSkillScores");
                });

            modelBuilder.Entity("STEM.Web.Models.Banner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LinkUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Banners__3214EC070C7B5A18");

                    b.ToTable("Banners");
                });

            modelBuilder.Entity("STEM.Web.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Classes__3214EC07C8A04ADF");

                    b.HasIndex("CourseId");

                    b.HasIndex("TeacherId");

                    b.HasIndex(new[] { "ClassCode" }, "UQ__Classes__2ECD4A55BB375314")
                        .IsUnique();

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("STEM.Web.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MinStudents")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Summary")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte>("TargetAgeMax")
                        .HasColumnType("tinyint");

                    b.Property<byte>("TargetAgeMin")
                        .HasColumnType("tinyint");

                    b.Property<int>("TotalSessions")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Courses__3214EC0715D4E233");

                    b.HasIndex(new[] { "Code" }, "UQ__Courses__A25C5AA769A22348")
                        .IsUnique();

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("STEM.Web.Models.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrollDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Enrollme__3214EC07EA03FFEB");

                    b.HasIndex("ClassId");

                    b.HasIndex(new[] { "StudentId", "ClassId" }, "UQ_Enrollment_Student_Class")
                        .IsUnique();

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("STEM.Web.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.HasKey("Id")
                        .HasName("PK__Equipmen__3214EC07428901EF");

                    b.HasIndex("CategoryId");

                    b.HasIndex(new[] { "SerialNumber" }, "UQ__Equipmen__048A0008296303C3")
                        .IsUnique();

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("STEM.Web.Models.EquipmentBorrow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BorrowTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("BorrowerId")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReturnTime")
                        .HasColumnType("datetime");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Equipmen__3214EC07F1639B96");

                    b.HasIndex("BorrowerId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("SessionId");

                    b.ToTable("EquipmentBorrows");
                });

            modelBuilder.Entity("STEM.Web.Models.EquipmentCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Equipmen__3214EC0708814373");

                    b.ToTable("EquipmentCategories");
                });

            modelBuilder.Entity("STEM.Web.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FinalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Invoices__3214EC07A9A8E95F");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentId");

                    b.HasIndex(new[] { "InvoiceNo" }, "UQ__Invoices__D796B227747B5D19")
                        .IsUnique();

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("STEM.Web.Models.Lead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InterestedId")
                        .HasColumnType("int");

                    b.Property<string>("ParentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("Id")
                        .HasName("PK__Leads__3214EC07A2FCE2D2");

                    b.HasIndex("InterestedId");

                    b.ToTable("Leads");
                });

            modelBuilder.Entity("STEM.Web.Models.MaintenanceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<string>("Issue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReportedBy")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("Id")
                        .HasName("PK__Maintena__3214EC07F0FC039A");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("ReportedBy");

                    b.ToTable("MaintenanceLogs");
                });

            modelBuilder.Entity("STEM.Web.Models.PayRateConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseDifficulty")
                        .HasColumnType("int");

                    b.Property<decimal>("RatePerSession")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TeacherTier")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PayRateConfigs");
                });

            modelBuilder.Entity("STEM.Web.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("TransDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__Payments__3214EC073957C8E5");

                    b.HasIndex("InvoiceId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("STEM.Web.Models.PayrollRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Bonuses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Deductions")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<decimal>("SessionEarnings")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalValidSessions")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("PayrollRecords");
                });

            modelBuilder.Entity("STEM.Web.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Excerpt")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK__Posts__3214EC074776CE99");

                    b.HasIndex("AuthorId");

                    b.HasIndex(new[] { "Slug" }, "UQ__Posts__BC7B5FB60B72526D")
                        .IsUnique();

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("STEM.Web.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Roles__3214EC07EDAD7F9F");

                    b.HasIndex(new[] { "Name" }, "UQ__Roles__737584F621924AD9")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("STEM.Web.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(30);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_Rooms");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("STEM.Web.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssistantNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<string>("ClassMediaUrls")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("PayrollStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("SessionNo")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("TeachingMaterialUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Topic")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Sessions__3214EC074B24E950");

                    b.HasIndex("RoomId");

                    b.HasIndex(new[] { "ClassId", "Date" }, "IX_Sessions_ClassId_Date");

                    b.HasIndex(new[] { "Date" }, "IX_Sessions_Date");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("STEM.Web.Models.StudentProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("CurrentSchool")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("GuardianName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GuardianPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MedicalNotes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId")
                        .HasName("PK__StudentP__1788CC4CFA93FF51");

                    b.ToTable("StudentProfiles");
                });

            modelBuilder.Entity("STEM.Web.Models.TeacherProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal?>("BaseSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CustomSessionRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SalaryTier")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("TeacherProfiles");
                });

            modelBuilder.Entity("STEM.Web.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC071248A9EA");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Username" }, "UQ__Users__536C85E4F7CBAA04")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("STEM.Web.Models.Attendance", b =>
                {
                    b.HasOne("STEM.Web.Models.Session", "Session")
                        .WithMany("Attendances")
                        .HasForeignKey("SessionId")
                        .IsRequired()
                        .HasConstraintName("FK_Attendances_Sessions");

                    b.HasOne("STEM.Web.Models.User", "Student")
                        .WithMany("Attendances")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_Attendances_Student");

                    b.Navigation("Session");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("STEM.Web.Models.AttendanceSkillScore", b =>
                {
                    b.HasOne("STEM.Web.Models.Attendance", "Attendance")
                        .WithMany("SkillScores")
                        .HasForeignKey("AttendanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AttendanceSkillScores_Attendances");

                    b.Navigation("Attendance");
                });

            modelBuilder.Entity("STEM.Web.Models.Class", b =>
                {
                    b.HasOne("STEM.Web.Models.Course", "Course")
                        .WithMany("Classes")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK_Classes_Courses");

                    b.HasOne("STEM.Web.Models.User", "Teacher")
                        .WithMany("Classes")
                        .HasForeignKey("TeacherId")
                        .IsRequired()
                        .HasConstraintName("FK_Classes_Teacher");

                    b.Navigation("Course");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("STEM.Web.Models.Enrollment", b =>
                {
                    b.HasOne("STEM.Web.Models.Class", "Class")
                        .WithMany("Enrollments")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK_Enrollments_Classes");

                    b.HasOne("STEM.Web.Models.User", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_Enrollments_Student");

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("STEM.Web.Models.Equipment", b =>
                {
                    b.HasOne("STEM.Web.Models.EquipmentCategory", "Category")
                        .WithMany("Equipment")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Equipments_Category");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("STEM.Web.Models.EquipmentBorrow", b =>
                {
                    b.HasOne("STEM.Web.Models.User", "Borrower")
                        .WithMany("EquipmentBorrows")
                        .HasForeignKey("BorrowerId")
                        .IsRequired()
                        .HasConstraintName("FK_EqBorrows_Borrower");

                    b.HasOne("STEM.Web.Models.Equipment", "Equipment")
                        .WithMany("EquipmentBorrows")
                        .HasForeignKey("EquipmentId")
                        .IsRequired()
                        .HasConstraintName("FK_EqBorrows_Equipment");

                    b.HasOne("STEM.Web.Models.Session", "Session")
                        .WithMany("EquipmentBorrows")
                        .HasForeignKey("SessionId")
                        .IsRequired()
                        .HasConstraintName("FK_EqBorrows_Session");

                    b.Navigation("Borrower");

                    b.Navigation("Equipment");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("STEM.Web.Models.Invoice", b =>
                {
                    b.HasOne("STEM.Web.Models.Class", "Class")
                        .WithMany("Invoices")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK_Invoices_Class");

                    b.HasOne("STEM.Web.Models.User", "Student")
                        .WithMany("Invoices")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_Invoices_Student");

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("STEM.Web.Models.Lead", b =>
                {
                    b.HasOne("STEM.Web.Models.Course", "Interested")
                        .WithMany("Leads")
                        .HasForeignKey("InterestedId")
                        .HasConstraintName("FK_Leads_Course");

                    b.Navigation("Interested");
                });

            modelBuilder.Entity("STEM.Web.Models.MaintenanceLog", b =>
                {
                    b.HasOne("STEM.Web.Models.Equipment", "Equipment")
                        .WithMany("MaintenanceLogs")
                        .HasForeignKey("EquipmentId")
                        .IsRequired()
                        .HasConstraintName("FK_MaintLogs_Equipment");

                    b.HasOne("STEM.Web.Models.User", "ReportedByNavigation")
                        .WithMany("MaintenanceLogs")
                        .HasForeignKey("ReportedBy")
                        .IsRequired()
                        .HasConstraintName("FK_MaintLogs_Reporter");

                    b.Navigation("Equipment");

                    b.Navigation("ReportedByNavigation");
                });

            modelBuilder.Entity("STEM.Web.Models.Payment", b =>
                {
                    b.HasOne("STEM.Web.Models.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .IsRequired()
                        .HasConstraintName("FK_Payments_Invoice");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("STEM.Web.Models.PayrollRecord", b =>
                {
                    b.HasOne("STEM.Web.Models.User", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("STEM.Web.Models.Post", b =>
                {
                    b.HasOne("STEM.Web.Models.User", "Author")
                        .WithMany("Posts")
                        .HasForeignKey("AuthorId")
                        .IsRequired()
                        .HasConstraintName("FK_Posts_Author");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("STEM.Web.Models.Session", b =>
                {
                    b.HasOne("STEM.Web.Models.Class", "Class")
                        .WithMany("Sessions")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK_Sessions_Classes");

                    b.HasOne("STEM.Web.Models.Room", "Room")
                        .WithMany("Sessions")
                        .HasForeignKey("RoomId")
                        .HasConstraintName("FK_Sessions_Rooms");

                    b.Navigation("Class");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("STEM.Web.Models.StudentProfile", b =>
                {
                    b.HasOne("STEM.Web.Models.User", "User")
                        .WithOne("StudentProfile")
                        .HasForeignKey("STEM.Web.Models.StudentProfile", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK_StudentProfiles_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("STEM.Web.Models.TeacherProfile", b =>
                {
                    b.HasOne("STEM.Web.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("STEM.Web.Models.User", b =>
                {
                    b.HasOne("STEM.Web.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_Users_Roles");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("STEM.Web.Models.Attendance", b =>
                {
                    b.Navigation("SkillScores");
                });

            modelBuilder.Entity("STEM.Web.Models.Class", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Invoices");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("STEM.Web.Models.Course", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Leads");
                });

            modelBuilder.Entity("STEM.Web.Models.Equipment", b =>
                {
                    b.Navigation("EquipmentBorrows");

                    b.Navigation("MaintenanceLogs");
                });

            modelBuilder.Entity("STEM.Web.Models.EquipmentCategory", b =>
                {
                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("STEM.Web.Models.Invoice", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("STEM.Web.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("STEM.Web.Models.Room", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("STEM.Web.Models.Session", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("EquipmentBorrows");
                });

            modelBuilder.Entity("STEM.Web.Models.User", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Classes");

                    b.Navigation("Enrollments");

                    b.Navigation("EquipmentBorrows");

                    b.Navigation("Invoices");

                    b.Navigation("MaintenanceLogs");

                    b.Navigation("Posts");

                    b.Navigation("StudentProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
